title: Songbai Cai's Homepage
page-top-title: A disciple of the Turtle Hermit — mastering the art of science and martial spirit
top-section-bg-text: Endless training, boundless exploration.
home-subtitle: Cai Songbai&nbsp;|&nbsp;Research Areas: Artificial Intelligence · Data Science
copyright-text: '&copy; Songbai Cai 2023–2025. All Rights Reserved.'
email: caisongbai@126.com
