title: Songbai Cai's Homepage
page-top-title: Woodman
top-section-bg-text: 'Endless training, boundless exploration'
home-subtitle: Cai Songbai&nbsp;|&nbsp;Research Areas: Artificial Intelligence · Data Science
email: caisongbai@126.com
copyright-text: '&copy; Songbai Cai 2023–2025. All Rights Reserved.'
